export const ASSIGNED_TASK_LIST_REQUEST = 'ASSIGNED_TASK_LIST_REQUEST'
export const ASSIGNED_TASK_LIST_SUCCESS = 'ASSIGNED_TASK_LIST_SUCCESS'
export const ASSIGNED_TASK_LIST_FAIL = 'ASSIGNED_TASK_LIST_FAIL'